# Generated by Django 5.2.4 on 2025-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='tipo',
            field=models.CharField(choices=[('clase', 'Clase'), ('descanso', 'Descanso'), ('almuerzo', 'Almuerzo')], default='clase', max_length=20),
        ),
    ]
