# Generated by Django 5.2.5 on 2025-08-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_bloquehorario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aula_fija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to='horarios.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='bloquehorario',
            unique_together={('numero', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('curso', 'dia', 'bloque'), ('profesor', 'dia', 'bloque')},
        ),
    ]
