# Generated by Django 5.2.5 on 2025-08-12 14:38

import django.core.validators
import horarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_curso_aula_fija_alter_bloquehorario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='capacidad',
            field=models.IntegerField(default=40, validators=[horarios.models.validate_capacidad_aula]),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El número de bloque debe ser al menos 1')]),
        ),
        migrations.AlterField(
            model_name='configuracioncolegio',
            name='bloques_por_dia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Debe tener al menos 1 bloque por día'), django.core.validators.MaxValueValidator(12, 'No puede tener más de 12 bloques por día')]),
        ),
        migrations.AlterField(
            model_name='configuracioncolegio',
            name='duracion_bloque',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30, 'La duración mínima es 30 minutos'), django.core.validators.MaxValueValidator(120, 'La duración máxima es 120 minutos')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadprofesor',
            name='bloque_fin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El bloque final debe ser al menos 1')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadprofesor',
            name='bloque_inicio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El bloque de inicio debe ser al menos 1')]),
        ),
        migrations.AlterField(
            model_name='horario',
            name='bloque',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'El bloque debe ser al menos 1')]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='bloques_por_semana',
            field=models.IntegerField(validators=[horarios.models.validate_bloques_por_semana]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[horarios.models.validate_nombre_materia]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[horarios.models.validate_nombre_profesor]),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadprofesor',
            unique_together={('profesor', 'dia')},
        ),
        migrations.AlterUniqueTogether(
            name='materiagrado',
            unique_together={('grado', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='materiaprofesor',
            unique_together={('profesor', 'materia')},
        ),
    ]
