# Generated by Django 5.2.7 on 2024-01-15 10:00:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_aula_capacidad_alter_bloquehorario_numero_and_more'),
    ]

    operations = [
        # Índice compuesto para BloqueHorario (dia, bloque)
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['numero', 'tipo'], name='bloque_horario_numero_tipo_idx'),
        ),
        
        # Índice para búsquedas por tipo de bloque
        migrations.AddIndex(
            model_name='bloquehorario',
            index=models.Index(fields=['tipo'], name='bloque_horario_tipo_idx'),
        ),
        
        # Índice para disponibilidad de profesores
        migrations.AddIndex(
            model_name='disponibilidadprofesor',
            index=models.Index(fields=['profesor', 'dia'], name='disponibilidad_profesor_dia_idx'),
        ),
        
        # Índice para búsquedas por rango de bloques
        migrations.AddIndex(
            model_name='disponibilidadprofesor',
            index=models.Index(fields=['bloque_inicio', 'bloque_fin'], name='disponibilidad_bloque_rango_idx'),
        ),
        
        # Índice para materias por grado
        migrations.AddIndex(
            model_name='materiagrado',
            index=models.Index(fields=['grado', 'materia'], name='materia_grado_grado_materia_idx'),
        ),
        
        # Índice para materias por profesor
        migrations.AddIndex(
            model_name='materiaprofesor',
            index=models.Index(fields=['materia', 'profesor'], name='materia_profesor_materia_profesor_idx'),
        ),
        
        # Índice para cursos por grado
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['grado'], name='curso_grado_idx'),
        ),
        
        # Índice para cursos por aula fija
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['aula_fija'], name='curso_aula_fija_idx'),
        ),
        
        # Índice para horarios por curso
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['curso'], name='horario_curso_idx'),
        ),
        
        # Índice para horarios por profesor
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['profesor'], name='horario_profesor_idx'),
        ),
        
        # Índice para horarios por día
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['dia'], name='horario_dia_idx'),
        ),
        
        # Índice para horarios por bloque
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['bloque'], name='horario_bloque_idx'),
        ),
        
        # Índice compuesto para búsquedas rápidas de horarios
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['curso', 'dia'], name='horario_curso_dia_idx'),
        ),
        
        # Índice compuesto para búsquedas de disponibilidad
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['profesor', 'dia'], name='horario_profesor_dia_idx'),
        ),
    ] 