# Generated by Django 5.2.7 on 2024-01-15 11:00:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_optimizacion_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('semilla', models.IntegerField()),
                ('poblacion_size', models.IntegerField()),
                ('generaciones', models.IntegerField()),
                ('prob_cruce', models.FloatField()),
                ('prob_mutacion', models.FloatField()),
                ('elite', models.IntegerField()),
                ('paciencia', models.IntegerField()),
                ('workers', models.IntegerField()),
                ('tournament_size', models.IntegerField()),
                ('random_immigrants_rate', models.FloatField()),
                ('peso_huecos', models.FloatField()),
                ('peso_primeras_ultimas', models.FloatField()),
                ('peso_balance_dia', models.FloatField()),
                ('peso_bloques_semana', models.FloatField()),
                ('exito', models.BooleanField(default=False)),
                ('fitness_final', models.FloatField()),
                ('generaciones_completadas', models.IntegerField()),
                ('convergencia', models.BooleanField(default=False)),
                ('tiempo_total_s', models.FloatField()),
                ('num_solapes', models.IntegerField(default=0)),
                ('num_huecos', models.IntegerField(default=0)),
                ('porcentaje_primeras_ultimas', models.FloatField(default=0.0)),
                ('desviacion_balance_dia', models.FloatField(default=0.0)),
                ('estado_sistema_hash', models.CharField(max_length=64)),
                ('num_cursos', models.IntegerField()),
                ('num_profesores', models.IntegerField()),
                ('num_materias', models.IntegerField()),
                ('comentarios', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-timestamp_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='trackercorrida',
            index=models.Index(fields=['exito', 'fitness_final'], name='tracker_corrida_exito_fitness_idx'),
        ),
        migrations.AddIndex(
            model_name='trackercorrida',
            index=models.Index(fields=['semilla', 'timestamp_inicio'], name='tracker_corrida_semilla_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='trackercorrida',
            index=models.Index(fields=['estado_sistema_hash'], name='tracker_corrida_estado_sistema_idx'),
        ),
    ] 