# Generated by Django 5.2.5 on 2025-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_tracker_corrida'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bloquehorario',
            name='bloque_horario_numero_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloquehorario',
            name='bloque_horario_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='curso_grado_idx',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='curso_aula_fija_idx',
        ),
        migrations.RemoveIndex(
            model_name='disponibilidadprofesor',
            name='disponibilidad_profesor_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='disponibilidadprofesor',
            name='disponibilidad_bloque_rango_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_curso_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_profesor_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_bloque_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_curso_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_profesor_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='materiagrado',
            name='materia_grado_grado_materia_idx',
        ),
        migrations.RemoveIndex(
            model_name='materiaprofesor',
            name='materia_profesor_materia_profesor_idx',
        ),
        migrations.RenameIndex(
            model_name='trackercorrida',
            new_name='horarios_tr_exito_d2a356_idx',
            old_name='tracker_corrida_exito_fitness_idx',
        ),
        migrations.RenameIndex(
            model_name='trackercorrida',
            new_name='horarios_tr_semilla_bdb105_idx',
            old_name='tracker_corrida_semilla_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='trackercorrida',
            new_name='horarios_tr_estado__c93c26_idx',
            old_name='tracker_corrida_estado_sistema_idx',
        ),
    ]
