# Generated by Django 5.2.5 on 2025-08-13 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_remove_bloquehorario_bloque_horario_numero_tipo_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoMateriaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloques_requeridos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=15)),
                ('bloque', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('clase', 'Clase'), ('descanso', 'Descanso'), ('almuerzo', 'Almuerzo')], default='clase', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'bloque'], name='horarios_sl_dia_fb3fcd_idx')],
                'unique_together': {('dia', 'bloque')},
            },
        ),
        migrations.CreateModel(
            name='ProfesorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.slot')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.slot'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('curso', 'slot'), name='uniq_horario_curso_slot'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('profesor', 'slot'), name='uniq_horario_profesor_slot'),
        ),
        migrations.AddIndex(
            model_name='cursomateriarequerida',
            index=models.Index(fields=['curso', 'materia'], name='horarios_cu_curso_i_3ddd0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cursomateriarequerida',
            unique_together={('curso', 'materia')},
        ),
        migrations.AddIndex(
            model_name='profesorslot',
            index=models.Index(fields=['profesor', 'slot'], name='horarios_pr_profeso_2910cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profesorslot',
            unique_together={('profesor', 'slot')},
        ),
    ]
