# Generated by Django 5.2.5 on 2025-08-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_cursomateriarequerida_slot_profesorslot_horario_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_json', models.JSONField()),
                ('dataset_hash', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=20)),
                ('best_obj', models.FloatField(default=0.0)),
                ('log_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['started_at'], name='horarios_ru_started_fc10e7_idx'), models.Index(fields=['status'], name='horarios_ru_status_18b786_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField()),
                ('best', models.FloatField()),
                ('avg', models.FloatField()),
                ('fill_pct', models.FloatField()),
                ('conflicts', models.IntegerField(default=0)),
                ('t_s', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='horarios.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'gen'], name='horarios_ru_run_id_26d3da_idx')],
                'unique_together': {('run', 'gen')},
            },
        ),
    ]
