# Generated by Django 5.0.2 on 2026-02-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0010_materias_relleno_y_reglas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunMetric',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
